class ConflictError(Exception):
        pass


class InvalidError(Exception):
    pass
